### ISSUE TITLE
Town info screen crashes

### ISSUE THREAD

**Issue by justinpchang** [codeforbtv/green-up-app-old#431]
Introduced in #428 

Town Information tab crashes with error TypeError: el.getNode is not a function. This is probably the most severe bug. Also not sure what's supposed to happen here.

![image](https://user-images.githubusercontent.com/4704389/233749234-f840a720-06ca-426e-882d-e343a69d2a5a.png)

**Comment by justinpchang** [comment]
This button opens trash disposal screen, so it is the same bug as #432
